// <auto-generated />
using System;
using Deposit_2.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Deposit_2.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20191219204332_TempPassword")]
    partial class TempPassword
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085");

            modelBuilder.Entity("Deposit_2.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BlockExpires");

                    b.Property<string>("Email");

                    b.Property<int>("FailedAuthRetryCount");

                    b.Property<string>("FiltersConfig");

                    b.Property<string>("Password");

                    b.Property<string>("ProfileConfig");

                    b.Property<string>("TempPassword");

                    b.Property<DateTime>("TempPasswordValidTillDate");

                    b.Property<string>("Username");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
