# Generated by Django 2.0.6 on 2019-11-04 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField()),
                ('capitalization', models.BooleanField()),
                ('replenishment_possibility', models.BooleanField()),
                ('early_recall', models.BooleanField()),
                ('opening_online', models.BooleanField()),
                ('prolongation', models.BooleanField()),
                ('partial_withdrawal', models.BooleanField()),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Bank')),
                ('categories', models.ManyToManyField(to='api.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('currency', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='deposit',
            name='rates',
            field=models.ManyToManyField(to='api.Rate'),
        ),
    ]
